
import {
  RATE_BELOW_1500,
  RATE_ABOVE_1500,
  THRESHOLD_RATE_CHANGE,
  RETAIL_CHARGE,
  RETAIL_CHARGE_THRESHOLD,
  TAX_RATE,
  TAX_THRESHOLD,
  KWTBB_RATE,
  DISCOUNT_TABLE,
  PANEL_WATTAGE,
  PEAK_SUN_HOURS,
  BATTERY_CAPACITY_KWH,
  SYSTEM_PRICING,
  BATTERY_COST_CASH,
  MANUAL_BACKUP_BOX_SINGLE_PHASE_RM,
  MANUAL_BACKUP_BOX_THREE_PHASE_RM,
  AUGUST_PROMO_SYSTEM_DISCOUNT,
  AUGUST_PROMO_SYSTEM_DISCOUNT_ZERO_BAT,
  AUGUST_PROMO_BATTERY_UNIT_DISCOUNT,
  THREE_PHASE_INVERTER_UPGRADE_5_TO_8KW_RM,
  THREE_PHASE_INVERTER_UPGRADE_8_TO_10KW_RM,
  THREE_PHASE_INVERTER_UPGRADE_10_TO_12KW_RM,
  THREE_PHASE_INVERTER_UPGRADE_12_TO_15KW_RM,
  THREE_PHASE_INVERTER_UPGRADE_20_TO_25KW_RM
} from '../constants';
import { BillBreakdown, SimulationResult, PricingTier } from '../types';

/**
 * Calculates the base charge (tariff).
 * The rate is determined by the TOTAL monthly usage (Flat Rate Tier).
 * If total usage > 1500, the higher rate applies to ALL units.
 */
const calculateBaseCharge = (kwhToPrice: number, totalMonthlyUsage: number): number => {
  if (kwhToPrice <= 0) return 0;

  // Determine rate based on Total Monthly Usage
  const rate = totalMonthlyUsage > THRESHOLD_RATE_CHANGE
    ? RATE_ABOVE_1500
    : RATE_BELOW_1500;

  return kwhToPrice * rate;
};

/**
 * Helper to get the applicable discount rate (in RM) based on total usage.
 * Returns negative value or 0.
 */
const getDiscountRateRm = (totalKwh: number): number => {
  if (totalKwh <= 0) return 0;
  const block = DISCOUNT_TABLE.find(b => totalKwh >= b.min && totalKwh <= b.max);
  return block ? (block.discountSen / 100) : 0;
};

/**
 * Main function to calculate the full bill breakdown.
 */
export const calculateBill = (totalKwh: number, exportKwh: number = 0): BillBreakdown => {
  if (totalKwh <= 0 && exportKwh <= 0) {
    return {
      baseCharge: 0,
      retailCharge: 0,
      discount: 0,
      serviceTax: 0,
      kwtbb: 0,
      exportCredit: 0,
      exportUnits: 0,
      eeIncentiveAdjustment: 0,
      subtotal: 0,
      finalTotal: 0,
      units: 0
    };
  }

  // --- 1. Determine Shared Rates ---
  const discountRate = getDiscountRateRm(totalKwh);

  // --- 2. Calculate Full Bill Components ---
  // Pass totalKwh as the second argument to determine the tier for the whole bill
  const totalBaseCharge = calculateBaseCharge(totalKwh, totalKwh);
  const retailChargeTotal = totalKwh > RETAIL_CHARGE_THRESHOLD ? RETAIL_CHARGE : 0;
  const totalDiscount = totalKwh * discountRate; // Apply rate to full usage

  const subtotalTotal = totalBaseCharge + retailChargeTotal + totalDiscount;

  // --- 3. Calculate Service Tax (Split Logic) ---
  // Tax applies to the portion of the bill generated by usage > 600kWh.
  // Taxable Amount = (Subtotal for Total Usage) - (Subtotal for First 600kWh).
  // CRITICAL: The "Subtotal for First 600kWh" must use the SAME rates (Base Rate & Incentive)
  // as the total bill, because those rates are determined by the TOTAL monthly usage.

  let serviceTax = 0;

  if (totalKwh > TAX_THRESHOLD) {
    const kwhExempt = TAX_THRESHOLD; // 600

    // Base charge for the exempt portion, using the rate determined by TOTAL usage
    const baseExempt = calculateBaseCharge(kwhExempt, totalKwh);

    // Discount for the exempt portion, using the rate determined by TOTAL usage
    const discountExempt = kwhExempt * discountRate;

    // Retail charge is 0 for the first 600
    const retailExempt = 0;

    const subtotalExempt = baseExempt + retailExempt + discountExempt;

    // Taxable amount is the difference
    const taxableAmount = subtotalTotal - subtotalExempt;

    serviceTax = Math.max(0, taxableAmount * TAX_RATE);
  } else {
    serviceTax = 0;
  }

  // --- 4. KWTBB (Renewable Energy Fund) ---
  // 1.6% of (Base + Discount) - before tax
  const kwtbbBase = totalBaseCharge + totalDiscount;
  const kwtbb = Math.max(0, kwtbbBase * KWTBB_RATE);

  // --- 5. Export Credit ---
  // New Rule:
  // if new import is <=1500kwh, use RM 0.2703 (27.03 sen) per kwh
  // if new import is >1500kwh, use RM 0.3703 (37.03 sen) per kwh
  const currentExportRate = totalKwh > THRESHOLD_RATE_CHANGE ? 0.3703 : 0.2703;
  // Cap export credit calculation at the import amount (totalKwh)
  const creditUnits = Math.min(exportKwh, totalKwh);
  const exportCredit = creditUnits * currentExportRate * -1; // Negative value for deduction

  // --- 6. EE Incentive Adjustment for Export ---
  // Formula: IF(new export=0, 0, IF(new export > new import, -EE Incentive, -new export * (EE Incentive / new import)))
  // Note: totalDiscount is the "EE Incentive" (negative value).
  let eeIncentiveAdjustment = 0;

  if (exportKwh === 0) {
    eeIncentiveAdjustment = 0;
  } else if (exportKwh > totalKwh) {
    eeIncentiveAdjustment = -totalDiscount; // Becomes positive
  } else {
    // totalKwh must be > 0 here because if totalKwh=0, exportKwh(>0) > totalKwh would catch above
    eeIncentiveAdjustment = -exportKwh * (totalDiscount / (totalKwh || 1));
  }

  // --- 7. Final Total ---
  let finalTotal = subtotalTotal + serviceTax + kwtbb + exportCredit + eeIncentiveAdjustment;

  // Logic Fix: Ensure Final Bill is not negative
  finalTotal = Math.max(0, finalTotal);

  return {
    baseCharge: totalBaseCharge,
    retailCharge: retailChargeTotal,
    discount: totalDiscount,
    serviceTax: serviceTax,
    kwtbb: kwtbb,
    exportCredit: exportCredit,
    exportUnits: exportKwh,
    eeIncentiveAdjustment: eeIncentiveAdjustment,
    subtotal: subtotalTotal,
    finalTotal: finalTotal,
    units: totalKwh
  };
};

export const simulateSolar = (
  monthlyUsage: number,
  daytimePercentage: number,
  panelCount: number,
  batteryCount: number
): SimulationResult => {
  // 1. Calculate D and N
  const D = monthlyUsage * (daytimePercentage / 100);
  const N = monthlyUsage * (1 - (daytimePercentage / 100));

  // 2. Calculate S (Solar Generation)
  // 650W panels = 0.65 kWp; kWh per month = kW × peak sun hours × 30
  const kwPerPanelHour = PANEL_WATTAGE / 1000;
  const S = panelCount * kwPerPanelHour * PEAK_SUN_HOURS * 30;

  // 3. Calculate B (Total Battery Capacity Throughput)
  // quantity × usable kWh/day × 30
  const B = batteryCount * BATTERY_CAPACITY_KWH * 30;

  // 4. Calculate R (Remaining Solar)
  const R = S - D;

  // 5. Calculate Battery In
  // Logic simplified: Max(0, Min(B, R))
  const batteryIn = Math.max(0, Math.min(B, R));

  // 6. Calculate Battery Out (Consumed during night)
  // Formula: IF(D>S, 0, IF(B>(S-D), S-D, B)) * 0.9
  const batteryOut = batteryIn * 0.9;

  // 7. Calculate Export
  // Logic: R - batteryIn.
  const exportRaw = Math.max(0, R - batteryIn);
  // Round export to integer as requested
  const exportKwh = Math.round(exportRaw);

  // 8. Calculate New Import
  // IF R < 0: MAX(0, N - batteryOut) - R
  // IF R >= 0: MAX(0, N - batteryOut)
  let newImportRaw = 0;
  if (R < 0) {
    // Note: batteryOut is 0 when R < 0
    newImportRaw = Math.max(0, N - batteryOut) - R;
  } else {
    // Note: batteryOut reduces Night load
    newImportRaw = Math.max(0, N - batteryOut);
  }

  // Round new import to integer as requested
  const newImport = Math.round(newImportRaw);

  // 9. Calculate New Bill
  const originalBill = calculateBill(monthlyUsage, 0);
  const newBill = calculateBill(newImport, exportKwh);

  // Data for Charts
  // Solar Direct Use: Amount of Solar used directly by D.
  const solarDirect = Math.min(S, D);

  // Chart battery visualization
  const chartBattery = Math.min(batteryOut, N);

  return {
    originalBill,
    newBill,
    solarGenerationMonthly: S,
    solarUtilized: solarDirect,
    batteryDischarge: chartBattery,
    gridImport: newImport,
    monthlySavings: originalBill.finalTotal - newBill.finalTotal,
    demandDay: D,
    demandNight: N
  };
};

/**
 * Reverse calculate kWh from a target Bill Amount using Binary Search.
 * Accurate within +/- RM0.05
 */
export const getKwhFromBill = (targetBill: number): number => {
  if (targetBill <= 0) return 0;

  let low = 0;
  let high = 10000; // Reasonable max
  let mid = 0;
  let iterations = 0;

  while (low <= high && iterations < 50) {
    mid = (low + high) / 2;
    const bill = calculateBill(mid, 0).finalTotal;

    if (Math.abs(bill - targetBill) < 0.05) {
      return Math.round(mid);
    }

    if (bill < targetBill) {
      low = mid;
    } else {
      high = mid;
    }
    iterations++;
  }
  return Math.round(mid);
};

export interface CalculateSystemCostOptions {
  augustPromo?: boolean;
  /** SuRIA Home government rebate: flat −RM3000 off both cash and CC price. */
  suriaHomeRebate?: boolean;
  /** When true, skips all auto-inverter upgrade logic and uses the sheet inverter size as-is. */
  skipInverterUpgrade?: boolean;
}

/**
 * THE single cash -> CC conversion. Everything — add-ons, batteries, inverter upgrades, promo
 * discounts, rebates — is applied to the CASH price first; the CC price is then derived from that
 * final figure with this function. Never add to or subtract from a CC price directly: to show a
 * "before discount" CC, derive it from the corresponding "before discount" CASH.
 */
export const CC_DIVISOR = 0.925;
export const deriveCcFromCash = (cash: number): number =>
  Math.ceil(cash / CC_DIVISOR / 10) * 10;

/** 60-month credit-card plan: same derivation, lower divisor. */
export const CC_60M_DIVISOR = 0.9;
export const deriveCc60FromCash = (cash: number): number =>
  Math.ceil(cash / CC_60M_DIVISOR / 10) * 10;

/** System-level RM discount when the August Promo is active. */
export const getAugustPromoSystemDiscount = (batteries: number): number =>
  batteries >= 1
    ? AUGUST_PROMO_SYSTEM_DISCOUNT
    : AUGUST_PROMO_SYSTEM_DISCOUNT_ZERO_BAT;

/** Per-battery RM discount when the August Promo is active. */
export const getAugustPromoBatteryDiscount = (batteries: number): number =>
  batteries * AUGUST_PROMO_BATTERY_UNIT_DISCOUNT;

/**
 * Total August Promo discount. Like every other discount it comes off cash, and the CC price is
 * then derived from the reduced cash — so CC always stays at cash / 0.925.
 */
export const getAugustPromoDiscount = (batteries: number): number =>
  getAugustPromoSystemDiscount(batteries) + getAugustPromoBatteryDiscount(batteries);

/**
 * Lookup system cost based on panel count and battery count.
 * Includes Three-Phase price adjustments and Inverter Upgrade logic.
 */
export const calculateSystemCost = (
  panels: number,
  batteries: number,
  phase: 'single' | 'three' = 'single',
  options?: CalculateSystemCostOptions
) => {
  const tier = SYSTEM_PRICING.find(p => p.panels === panels);
  if (!tier) return null;

  let cashPrice = tier.cashPrice;
  let inverterSize = tier.inverterSize;

  const hasExplicitThreePhase =
    tier.threePhaseCashPrice != null && tier.threePhaseCcPrice != null;

  // Sheet tier prices are the NO-BATTERY system (panels, inverter, install). A battery system is:
  //   sheet price + manual backup box (once) + BATTERY_COST_CASH per battery.
  // e.g. 14 panels single phase + 2 batteries = 22333 + 1600 + 8600 + 8600.
  if (phase === 'three' && hasExplicitThreePhase) {
    inverterSize = tier.threePhaseInverterSize ?? tier.inverterSize;
    cashPrice = tier.threePhaseCashPrice!;
  }

  // Mandatory whenever batteries are fitted; charged once, not per battery.
  const manualBackupBoxRM =
    batteries > 0
      ? phase === 'single'
        ? MANUAL_BACKUP_BOX_SINGLE_PHASE_RM
        : MANUAL_BACKUP_BOX_THREE_PHASE_RM
      : 0;

  // --- Single Phase Validation Rules ---
  // Note: Removed strict return null to prevent UI freezing.
  // Validation is now handled in PlanRecommender (for auto plans) and RecommendationCard (for user warning).

  const originalInverter = inverterSize;
  const systemKwp = panels * (PANEL_WATTAGE / 1000);
  let upgradeCost = 0;
  let isUpgraded = false;

  // --- 2. Inverter Upgrade Logic (Strict Capacity Limits) ---
  // Enforces capacity limits by upgrading inverter and adding cost.

  const hasBattery = batteries > 0;

  // Define Limits based on battery presence
  // Limits:             No Bat   |  With Bat
  // 5 kWac (1 Phase)  : 6.82     |  8.68   (Not upgraded automatically)
  // 8 kWac (3 Phase)  : 10.54    |  13.64
  // 10 kWac (3 Phase) : 13.64    |  16.74
  // 12 kWac (3 Phase) : 16.12    |  19.84
  // 15 kWac (3 Phase) : 20.46    |  24.80

  const limit8kW = hasBattery ? 13.64 : 10.54;
  const limit10kW = hasBattery ? 16.74 : 13.64;
  const limit12kW = hasBattery ? 19.84 : 16.12;

  if (!options?.skipInverterUpgrade) {
    if (phase === 'single') {
      // Single Phase Logic: DO NOT UPGRADE > 5kWac
    } else if (!hasExplicitThreePhase) {
      // Three Phase Cascading Logic (tiers 41+ without explicit three-phase sheet pricing)

      if (inverterSize.includes("8 kWac") && systemKwp > limit8kW) {
        inverterSize = "10 kWac Three Phase";
        upgradeCost += 300;
        isUpgraded = true;
      }
      if (inverterSize.includes("10 kWac") && systemKwp > limit10kW) {
        inverterSize = "12 kWac Three Phase";
        upgradeCost += 600;
        isUpgraded = true;
      }
      if (inverterSize.includes("12 kWac") && systemKwp > limit12kW) {
        inverterSize = "15 kWac Three Phase";
        upgradeCost += 800;
        isUpgraded = true;
      }

      // The 20 kWac sheet tiers run 41–60 panels, but from 50 panels the array outgrows the
      // inverter, so it steps up to 25 kWac. Driven by panel count rather than a kWp limit
      // because that is how the rule is quoted. Tiers 61+ already ship 25 kWac from the sheet,
      // so the upper bound never actually bites — it is stated to keep the rule readable.
      if (inverterSize.includes("20 kWac") && panels >= 50 && panels <= 60) {
        inverterSize = "25 kWac Three Phase";
        upgradeCost += THREE_PHASE_INVERTER_UPGRADE_20_TO_25KW_RM;
        isUpgraded = true;
      }
    }

    // Three-phase explicit-tier inverter auto-upgrades (panels 6–40), regardless of battery count.
    if (phase === 'three' && hasExplicitThreePhase) {
      let targetInverter = inverterSize;
      let stepCost = 0;
      if (panels >= 11 && panels <= 14) {
        targetInverter = '8 kWac Three Phase';
        stepCost = THREE_PHASE_INVERTER_UPGRADE_5_TO_8KW_RM;
      } else if (panels >= 18 && panels <= 21) {
        targetInverter = '10 kWac Three Phase';
        stepCost = THREE_PHASE_INVERTER_UPGRADE_8_TO_10KW_RM;
      } else if (panels >= 22 && panels <= 26) {
        targetInverter = '12 kWac Three Phase';
        stepCost = THREE_PHASE_INVERTER_UPGRADE_10_TO_12KW_RM;
      } else if (panels >= 27 && panels <= 32) {
        targetInverter = '15 kWac Three Phase';
        stepCost = THREE_PHASE_INVERTER_UPGRADE_12_TO_15KW_RM;
      }

      // Only treat as an upgrade when the sheet inverter is actually smaller than the
      // target. Some tiers (e.g. panels 12–14) already list the larger inverter in the
      // sheet, so re-applying it here would show a bogus "8 kWac → 8 kWac" upgrade and
      // double-charge the add-on cost that the sheet price already includes.
      if (targetInverter !== originalInverter) {
        inverterSize = targetInverter;
        upgradeCost += stepCost;
        isUpgraded = true;
      }
    }
  }

  const batCash = batteries * BATTERY_COST_CASH;

  // The Auto BackupBox upgrade is no longer handled here — it is a per-card Add-On
  // (see AUTO_BACKUP_BOX_UPGRADE_*_RM and AddOnItem in PlanRecommender).
  //
  // Manual backup box, batteries and any inverter upgrade build up the cash price; the CC price
  // is derived from it further down.
  let cash = cashPrice + manualBackupBoxRM + batCash + upgradeCost;

  let augustPromoSystemDiscount = 0;
  let augustPromoBatteryDiscount = 0;
  if (options?.augustPromo) {
    augustPromoSystemDiscount = getAugustPromoSystemDiscount(batteries);
    augustPromoBatteryDiscount = getAugustPromoBatteryDiscount(batteries);
    cash -= augustPromoSystemDiscount + augustPromoBatteryDiscount;
  }

  // Every add-on and every percentage-based discount has now landed on cash, so the credit-card
  // prices follow from this figure.
  let cc = deriveCcFromCash(cash);
  let cc60 = deriveCc60FromCash(cash);

  // The SuRIA rebate is the exception: it is a flat cash grant, not a discount on the system, so
  // it comes off AFTER the CC prices are derived and takes the same RM off all three. Deducting
  // it before derivation instead (as it used to be) inflated it to RM3,243 on the 36-month price
  // and RM3,333 on the 60-month one, because the divisor grossed it up.
  const suriaRebate = options?.suriaHomeRebate
    ? (phase === 'single' && (panels === 6 || panels === 7) ? 1800 : 3000)
    : 0;
  cash -= suriaRebate;
  cc -= suriaRebate;
  cc60 -= suriaRebate;

  const augustPromoDiscount = augustPromoSystemDiscount + augustPromoBatteryDiscount;

  return {
    cash,
    cc,
    cc60,
    inverterSize,
    tier,
    isUpgraded,
    originalInverter,
    upgradeCost,
    manualBackupBoxRM: manualBackupBoxRM > 0 ? manualBackupBoxRM : undefined,
    augustPromoDiscount: options?.augustPromo ? augustPromoDiscount : undefined,
    suriaRebate: suriaRebate > 0 ? suriaRebate : undefined
  };
};
