import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { QuotationDraft } from '../types';

export const generatePDF = (data: QuotationDraft) => {
  const doc = new jsPDF();
  
  // Colors
  const primaryColor = '#2563eb'; // blue-600
  const secondaryColor = '#64748b'; // slate-500
  
  // Helper to format currency
  const fmt = (num: number) => num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  // --- HEADER ---
  doc.setFontSize(22);
  doc.setTextColor(primaryColor);
  doc.setFont("helvetica", "bold");
  doc.text("SOLAR PROPOSAL", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(secondaryColor);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Commercial Calc", 14, 26);

  const rightMargin = 196;
  doc.text(`Date: ${data.date}`, rightMargin, 20, { align: 'right' });
  
  // --- CLIENT DETAILS ---
  let startY = 40;
  
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 32, 196, 32);

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text("Prepared For:", 14, startY);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  
  const clientInfo = [
    data.clientname || 'Client Name',
    data.clientcompany,
    data.contactno,
    data.email,
    `${data.addressline1 || ''} ${data.addressline2 || ''}`,
    data.addressline3
  ].filter(Boolean);

  let yOffset = startY + 6;
  clientInfo.forEach(line => {
      doc.text(line, 14, yOffset);
      yOffset += 5;
  });

  // --- SYSTEM SPECS ---
  // Right side column for system specs
  let rightColX = 110;
  let rightColY = startY;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("System Specifications:", rightColX, rightColY);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  
  const specs = [
      { label: "System Size:", val: `${data.systemsize} kWp` },
      { label: "Total Panels:", val: `${data.panel} pcs` },
      { label: "Inverter Size:", val: `${data.invertersize} kWac` },
      { label: "Inverter Brand:", val: data.inverterbrand || '-' },
  ];

  yOffset = rightColY + 6;
  specs.forEach(item => {
      doc.setFont("helvetica", "bold");
      doc.text(item.label, rightColX, yOffset);
      doc.setFont("helvetica", "normal");
      doc.text(item.val, rightColX + 35, yOffset);
      yOffset += 5;
  });

  // --- PRICING TABLE ---
  const price = Number(data.systemprice) || 0;
  const sst = price * 0.06;
  const total = price * 1.06;

  const tableStartY = Math.max(yOffset, 80) + 10;

  autoTable(doc, {
    startY: tableStartY,
    head: [['Description', 'Amount (RM)']],
    body: [
      [`Supply, Delivery & Installation of ${data.systemsize}kWp Solar PV System`, fmt(price)],
      [`SST (6%)`, fmt(sst)],
      [{ content: 'Total Payable', styles: { fontStyle: 'bold', textColor: [0, 0, 0] } }, { content: fmt(total), styles: { fontStyle: 'bold', textColor: [22, 163, 74] } }], // Green for total
    ],
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235] }, // Blue header
    columnStyles: {
        0: { cellWidth: 140 },
        1: { halign: 'right' }
    }
  });

  // --- TERMS / FOOTER ---
  const finalY = (doc as any).lastAutoTable.finalY + 20;
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text("Terms & Conditions:", 14, finalY);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text([
      "1. This quotation is valid for 14 days from the date of issue.",
      "2. Delivery lead time: 4-8 weeks upon confirmation.",
      "3. Payment terms: 50% deposit, 40% upon delivery, 10% upon commissioning."
  ], 14, finalY + 6);

  // Signature Line
  doc.setDrawColor(0, 0, 0);
  doc.line(14, finalY + 50, 80, finalY + 50);
  doc.text("Authorized Signature", 14, finalY + 55);

  // Save
  const safeName = (data.clientname || 'Quote').replace(/[^a-z0-9]/gi, '_');
  doc.save(`${safeName}.pdf`);
};